# @package _global_
defaults:
  - base@policy

  
policy:
  policy: maham
  use_ranking_pe: True

env:
  name: msprp
  num_agents: null
  goal: min-max

model:
  eval_per_agent: True
  eval_multistep: True