# @package _global_
env:
  env: msprp
  num_shelves: ???
  num_skus: ???
  num_storage_locations: ???
  num_agents: 1
  num_depots: 1
  min_demand: 0
  max_demand: 4
  min_supply: 1
  avg_supply_to_demand_ratio: 2.0


test:
  data_dir: 
    luttmann: ${paths.test_data_dir}/luttmann/${env.num_shelves}s-${env.num_skus}i-${env.num_storage_locations}p/dataset.pth