# @package _global_
defaults:
  - base_env@env
  - _self_


env:
  num_shelves: 
    - 5
    - 30
  num_skus: 
    - 3
    - 50
  num_storage_locations: 
    - 100
  pi: 0.9
  id: multi-env

train:
  batch_size: 64
  batch_size_valid: 64
  actor_lr: 0.00005