# @package _global_
defaults:
  - _self_
  - hydra: default.yaml # having hydra before logger in precedence order, so that logger can override run.dir
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - paths: default.yaml
  - env: jssp/6j-6m
  - model: transformer-sl


model:
  ref: ${policy.policy}_${model.algorithm} 

train:  
  train: true
  dataset_size: 1000
  batch_size: 200
  lr_scheduler:
    "MultiStepLR"
  lr_scheduler_kwargs:
    milestones: [7]
    gamma: 0.1
  optimizer_kwargs:
    policy_lr: 2e-4
    weight_decay: 1e-6
  max_grad_norm: 2.0
  epochs: 10

val:
  dataset_size: 1000
  batch_size: 500
  decode_type: greedy

test:
  dataset_size: 1000
  batch_size: 200
  num_decoding_samples: 100
  decode_type: sampling